# Token for the bot to log into
bot-token: ""

enable-features:
  roles: true

# Groups of roles to keep synced with members across servers
# Example: User A is given admin role in Server A. User A joins/is already in Server B. User A is given admin role in Server B.
# Might need to add in server here idk
synced-roles:
  admin:
    - 000000000000000000 #network admin role
    - 000000000000000000 #mc admin role
    - 000000000000000000 #r6 admin role
  moderator:
    - 000000000000000000 #network moderator role
    - 000000000000000000 #mc moderator role
    - 000000000000000000 #r6 moderator role

# Roles given to people in the main server for being in sub-servers
subguild-roles:
  main-guild: 000000000000000000 # guild id of main server (network)
  # Format: server-name: main-server-role-id
  role-map:
    minecraft: 0000000000000000
    rainbow: 0000000000000000

guilds:
  network:
    guild-id: 0000000000000000
    # Give a set of roles to people with specific roles
    common-roles:
      staff:
        roles-to-give:
          - 0000000000000000 # Staff
        role-list:
          - 0000000000000000 # Owner
          - 0000000000000000 # Admin
          - 0000000000000000 # Mod
  minecraft:
    guild-id: 0000000000000000
    # Give a set of roles to people with specific roles
    common-roles:
      staff:
        roles-to-give:
          - 0000000000000000 # Staff
        role-list:
          - 0000000000000000 # Owner
          - 0000000000000000 # Admin
          - 0000000000000000 # Mod
  rainbow:
    guild-id: 0000000000000000
    # Give a set of roles to people with specific roles
    common-roles:
      staff:
        roles-to-give:
          - 0000000000000000 # Staff
        role-list:
          - 0000000000000000 # Owner
          - 0000000000000000 # Admin
          - 0000000000000000 # Mod